### ISSUE TITLE
Uvoz podatkov

### ISSUE THREAD

**Issue by katarinabrilej** [M4rble/APPR-2019-20#2]
Opazila sem, da si datoteko za uvoz podatkov podatkiR.R shranil v mapo Podatki. Tu naj bi bile samo csv, html, ... datoteke, zato predlagam, da jo premakneš v mapo Uvoz. Prav tako bi bilo bolje da jo preimenuješ v podatkiR.r (torej končnica .r namesto .R), saj se preostale datoteke končajo z .r (v primeru da bi potem to datoteko poklical z podatkiR.R bi to na Windowsih in Macu delovalo, na Linuxu pa ne).

Prav tako v datoteki za uvoz ne rabiš posebej klicati knjižnic, ampak sledeča ukaza dodaš v datoteko libraries.r v mapi lib in potem to poženeš vsakič pred začetkom dela.
```
library(readr)
library(dplyr)
```
Svetujem ti tudi, da se v imenih stolpcev izogibaš šumnikov (Država zamenjaj z Drzava).
```
dostop_do_interneta <- read_csv("dostop_do_interneta.csv", col_names=c("Drzava", 2008:2019),
                                skip=1, na="-", locale=locale(encoding="Windows-1250"))
```

**Comment by M4rble** [comment]
Hvala za komentar, sem popravil, tako da bi moralo biti sedaj vse v redu.
